# Generated by Django 3.1.5 on 2021-08-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RpiDaqTestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100, verbose_name='Test Record Name')),
                ('testdate', models.DateTimeField(verbose_name='Date')),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RpiDaqData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_1', models.FloatField(null=True)),
                ('channel_2', models.FloatField(null=True)),
                ('channel_3', models.FloatField(null=True)),
                ('channel_4', models.FloatField(null=True)),
                ('channel_5', models.FloatField(null=True)),
                ('channel_6', models.FloatField(null=True)),
                ('channel_7', models.FloatField(null=True)),
                ('channel_8', models.FloatField(null=True)),
                ('channel_9', models.FloatField(null=True)),
                ('channel_11', models.FloatField(null=True)),
                ('channel_12', models.FloatField(null=True)),
                ('channel_13', models.FloatField(null=True)),
                ('channel_14', models.FloatField(null=True)),
                ('channel_15', models.FloatField(null=True)),
                ('channel_16', models.FloatField(null=True)),
                ('channel_17', models.FloatField(null=True)),
                ('channel_18', models.FloatField(null=True)),
                ('channel_19', models.FloatField(null=True)),
                ('channel_21', models.FloatField(null=True)),
                ('channel_22', models.FloatField(null=True)),
                ('channel_23', models.FloatField(null=True)),
                ('channel_24', models.FloatField(null=True)),
                ('channel_25', models.FloatField(null=True)),
                ('channel_26', models.FloatField(null=True)),
                ('channel_27', models.FloatField(null=True)),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpidaq.rpidaqtestdetails')),
            ],
        ),
    ]
