# Generated by Django 3.1.5 on 2021-08-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpidaq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpidaqdata',
            old_name='testid',
            new_name='testname',
        ),
    ]
