# Generated by Django 3.1.5 on 2021-08-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpidaq', '0002_auto_20210806_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpidaqdata',
            old_name='testname',
            new_name='testid',
        ),
    ]
