# Generated by Django 3.1.5 on 2021-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpidaq', '0003_auto_20210806_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpidaqdata',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
    ]
