# Generated by Django 3.1.5 on 2021-08-10 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rpidaq', '0004_rpidaqdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpidaqdata',
            name='date',
        ),
        migrations.AddField(
            model_name='rpidaqdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rpidaqdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
