# Generated by Django 3.1.5 on 2021-08-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpidaq', '0005_auto_20210810_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_18',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_21',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_23',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_26',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_27',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpidaqdata',
            name='channel_9',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
