# Generated by Django 3.1.5 on 2021-08-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpidaq', '0006_auto_20210810_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpidaqdata',
            name='channel_10',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
