# Generated by Django 3.1.5 on 2021-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpidaq', '0007_rpidaqdata_channel_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpidaqdata',
            name='channel_20',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
