# Generated by Django 2.2.4 on 2019-08-07 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default_user.jpg', upload_to='profile_pics')),
                ('flow_units', models.CharField(blank=True, default='Gallons per minute', max_length=20, null=True)),
                ('head_units', models.CharField(blank=True, default='Feet', max_length=20, null=True)),
                ('power_units', models.CharField(blank=True, default='Horsepower', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
