# Generated by Django 2.2.4 on 2019-08-07 20:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCurveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curvename', models.CharField(max_length=200)),
                ('bep_flow', models.FloatField(blank=True, null=True)),
                ('bep_head', models.FloatField(blank=True, null=True)),
                ('bep_efficiency', models.FloatField(blank=True, null=True)),
                ('peicl', models.FloatField(blank=True, null=True)),
                ('peivl', models.FloatField(blank=True, null=True)),
                ('pumptype', models.CharField(choices=[('FI', 'FI'), ('CI', 'CI'), ('KV', 'KV'), ('KS', 'KS'), ('TA', 'TA'), ('SKV', 'SKV'), ('SKS', 'SKS'), ('SFI', 'SFI'), ('SCI', 'SCI'), ('Circ', 'Residential Circulator')], max_length=100)),
                ('imp_dia', models.FloatField(blank=True, null=True)),
                ('fulltrim', models.BooleanField(default=False)),
                ('headcoeffs', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('effcoeffs', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('rpm', models.FloatField()),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.ReducedPumpTestDetails')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCurveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.FloatField()),
                ('head', models.FloatField()),
                ('power', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('curveid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingdata.MarketingCurveDetail')),
            ],
        ),
    ]
