# Generated by Django 2.2.4 on 2019-08-13 18:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcurvedetail',
            name='powercoeffs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[0], size=None),
            preserve_default=False,
        ),
    ]
