# Generated by Django 2.2.4 on 2019-08-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingdata', '0002_marketingcurvedetail_powercoeffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcurvedetail',
            name='ercl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingcurvedetail',
            name='ervl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
