# Generated by Django 2.2.4 on 2019-08-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketingdata', '0001_initial'),
        ('testdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('FI', 'FI'), ('CI', 'CI'), ('KV', 'KV'), ('KS', 'KS'), ('TA', 'TA'), ('SKV', 'SKV'), ('SKS', 'SKS'), ('SFI', 'SFI'), ('SCI', 'SCI'), ('Circ', 'Residential Circulator')], max_length=100)),
                ('pump_model', models.CharField(max_length=100)),
                ('design_iteration', models.CharField(blank=True, max_length=10, null=True)),
                ('speed', models.IntegerField(choices=[(1160, '1160 RPM'), (1450, '1450 RPM'), (1760, '1760 RPM'), (2900, '2900 RPM'), (3500, '3500 RPM')])),
                ('trim', models.FloatField()),
                ('engineering_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testdata.ReducedPumpTestDetails')),
                ('marketing_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketingdata.MarketingCurveDetail')),
            ],
        ),
    ]
