# Generated by Django 2.2.4 on 2019-08-13 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0001_initial'),
        ('marketingdata', '0001_initial'),
        ('pump', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='engineering_data',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='marketing_data',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='trim',
        ),
        migrations.CreateModel(
            name='PumpTrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim', models.FloatField()),
                ('engineering_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testdata.ReducedPumpTestDetails')),
                ('marketing_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketingdata.MarketingCurveDetail')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pump.Pump')),
            ],
        ),
        migrations.CreateModel(
            name='NPSHData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.FloatField()),
                ('npsh', models.FloatField()),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pump.Pump')),
            ],
        ),
    ]
