# Generated by Django 2.2.4 on 2019-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0002_auto_20190813_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='curve_number',
            field=models.CharField(default='00000', max_length=100),
        ),
    ]
