# Generated by Django 2.2.4 on 2019-08-15 18:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0003_pump_curve_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittalCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_motor_hp', models.FloatField()),
                ('min_motor_hp', models.FloatField()),
                ('eff_levels', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('power_manual_location_flows', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('power_manual_location_heads', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('x_axis_limits', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('y_axis_limits', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('l_per_sec_offset', models.FloatField()),
                ('created_on', models.DateTimeField(blank=True)),
                ('current_approved', models.BooleanField(default=False)),
                ('curve_svg', models.FileField(blank=True, null=True, upload_to='submittal_curves/')),
                ('curve_pdf', models.FileField(blank=True, null=True, upload_to='submittal_curves/')),
                ('curve_png', models.FileField(blank=True, null=True, upload_to='submittal_curves/')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pump.Pump')),
            ],
        ),
    ]
