# Generated by Django 2.2.4 on 2019-08-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0004_submittalcurve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittalcurve',
            old_name='curve_png',
            new_name='curve_jpg',
        ),
        migrations.RemoveField(
            model_name='submittalcurve',
            name='l_per_sec_offset',
        ),
        migrations.RemoveField(
            model_name='submittalcurve',
            name='x_axis_limits',
        ),
        migrations.RemoveField(
            model_name='submittalcurve',
            name='y_axis_limits',
        ),
        migrations.AddField(
            model_name='pump',
            name='curve_rev',
            field=models.CharField(default='00000', max_length=200),
        ),
        migrations.AddField(
            model_name='submittalcurve',
            name='x_axis_limit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittalcurve',
            name='y_axis_limit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
