# Generated by Django 2.2.4 on 2019-08-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0005_auto_20190816_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldTestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('testeng', models.CharField(blank=True, max_length=100, null=True)),
                ('teststnd', models.CharField(blank=True, max_length=100, null=True)),
                ('inpipedia_in', models.FloatField(blank=True, null=True)),
                ('outpipedia_in', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('testconfigs_id', models.IntegerField(blank=True, null=True)),
                ('pump_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('averaged', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
