# Generated by Django 2.2.4 on 2019-08-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0006_oldtestdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldtestdetails',
            name='averaged',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
