# Generated by Django 2.2.4 on 2019-08-27 03:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0007_auto_20190819_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittalcurve',
            name='curve_jpg',
        ),
        migrations.AddField(
            model_name='submittalcurve',
            name='curve_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittalcurve',
            name='npsh_flows',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittalcurve',
            name='npsh_npshs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
