# Generated by Django 2.2.4 on 2020-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0008_auto_20190827_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='series',
            field=models.CharField(choices=[('FI', 'FI'), ('CI', 'CI'), ('KV', 'KV'), ('KS', 'KS'), ('TA', 'TA'), ('SKV', 'SKV'), ('SKS', 'SKS'), ('SFI', 'SFI'), ('SCI', 'SCI'), ('Circ', 'Residential Circulator'), ('1600', '1600'), ('1900', '1900')], max_length=100),
        ),
    ]
