# Generated by Django 3.1.5 on 2024-09-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0009_auto_20200106_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='series',
            field=models.CharField(choices=[('FI', 'FI'), ('CI', 'CI'), ('KV', 'KV'), ('KS', 'KS'), ('TA', 'TA'), ('TS', 'TS'), ('TC', 'TC'), ('SKV', 'SKV'), ('SKS', 'SKS'), ('SFI', 'SFI'), ('SCI', 'SCI'), ('Circ', 'Residential Circulator'), ('1600', '1600'), ('1900', '1900'), ('HS', 'HS'), ('GT', 'GT')], max_length=100),
        ),
    ]
