# Generated by Django 2.2.4 on 2019-08-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawTestsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headfield', models.CharField(blank=True, max_length=20, null=True)),
                ('flowfield', models.CharField(blank=True, max_length=20, null=True)),
                ('powerfield', models.CharField(blank=True, max_length=20, null=True)),
                ('torquefield', models.CharField(blank=True, max_length=20, null=True)),
                ('headunits', models.CharField(blank=True, choices=[('ft', 'Feet of water'), ('m', 'meters of water')], max_length=10, null=True)),
                ('flowunits', models.CharField(blank=True, choices=[('gpm', 'Gallons per minute'), ('m3ph', 'Cubic meter per hour'), ('lpm', 'liters per minute')], max_length=20, null=True)),
                ('powerunits', models.CharField(blank=True, choices=[('W', 'Watts'), ('KW', 'Kilo Watts'), ('HP', 'Horsepower')], max_length=20, null=True)),
                ('tempunits', models.CharField(blank=True, choices=[('ftlbf', 'Feet Pound Force'), ('Nm', 'Newton meter')], max_length=20, null=True)),
                ('rpmfield', models.CharField(blank=True, max_length=20, null=True)),
                ('path', models.CharField(blank=True, max_length=400, null=True, verbose_name='URL')),
                ('testname', models.CharField(max_length=100, verbose_name='Test Record Name')),
                ('testdate', models.DateTimeField(verbose_name='Date')),
                ('datareduced', models.BooleanField(default=False, verbose_name='Data Reduced')),
                ('fileupload', models.BooleanField(blank=True, null=True, verbose_name='File Upload')),
                ('hidden', models.BooleanField(blank=True, null=True)),
                ('testdatatype', models.CharField(blank=True, choices=[('CE', 'Commercial Efficiency'), ('CP', 'Commercial Standard Performance'), ('RS1', 'Residential Stand 1'), ('RS2', 'Residential Stand 2'), ('CO', 'Commercial Outside Stand')], max_length=200, null=True, verbose_name='Test Stand')),
            ],
        ),
        migrations.CreateModel(
            name='ReducedPumpTestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=200)),
                ('testeng', models.CharField(blank=True, max_length=100, null=True)),
                ('testloop', models.CharField(blank=True, max_length=100, null=True)),
                ('discharge_pipe_dia', models.FloatField()),
                ('inlet_pipe_dia', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('testdate', models.DateTimeField()),
                ('bep_flow', models.FloatField(blank=True, null=True)),
                ('bep_head', models.FloatField(blank=True, null=True)),
                ('bep_efficiency', models.FloatField(blank=True, null=True)),
                ('peicl', models.FloatField(blank=True, null=True)),
                ('peivl', models.FloatField(blank=True, null=True)),
                ('pumptype', models.CharField(choices=[('FI', 'FI'), ('CI', 'CI'), ('KV', 'KV'), ('KS', 'KS'), ('TA', 'TA'), ('SKV', 'SKV'), ('SKS', 'SKS'), ('SFI', 'SFI'), ('SCI', 'SCI'), ('ESCC', 'End suction close-coupled'), ('ESFM', 'End suction frame mounted/own bearings'), ('IL', 'In-Line'), ('RSV', 'Radially split, multi-stage, vertical, in-line casing diffuser'), ('ST', 'Submersible turbine'), ('Circ', 'Residential Circulator')], max_length=100)),
                ('imp_dia', models.FloatField(blank=True, null=True)),
                ('fulltrim', models.BooleanField(default=False)),
                ('bearingframe', models.CharField(blank=True, choices=[('H', 'H Frame'), ('J', 'J Frame'), ('L', 'L Frame'), ('N', 'N Frame'), ('N/A', 'None')], max_length=10, null=True)),
                ('data_sources', models.ManyToManyField(related_name='used_in', to='testdata.RawTestsList')),
            ],
        ),
        migrations.CreateModel(
            name='ReducedPumpTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.FloatField()),
                ('head', models.FloatField()),
                ('power', models.FloatField()),
                ('temp', models.FloatField()),
                ('rpm', models.FloatField()),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.ReducedPumpTestDetails')),
            ],
        ),
    ]
