# Generated by Django 2.2.4 on 2020-01-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reducedpumptestdetails',
            name='data_sources',
            field=models.ManyToManyField(blank=True, null=True, related_name='used_in', to='testdata.RawTestsList'),
        ),
    ]
