# Generated by Django 2.2.4 on 2020-01-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0003_auto_20200117_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reducedpumptestdetails',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
