# Generated by Django 2.2.4 on 2020-06-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0004_auto_20200131_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reducedpumptestdata',
            name='rpm',
            field=models.FloatField(null=True),
        ),
    ]
